name: Auto-format
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with: { java-version: '11' }
      - name: Format code
        run: mvn spotless:apply
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format code" || echo "No changes to commit"
          git push
